# Generated by Django 4.2.20 on 2025-04-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
        ('orders', '0002_alter_deliverymethods_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.ManyToManyField(to='orders.paymentmethods', verbose_name='Способы оплаты')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Способы оплаты для товара',
                'verbose_name_plural': 'Способы оплаты для товаров',
            },
        ),
    ]
