# Generated by Django 4.2.20 on 2025-04-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productpaymentmethods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPaymentMethods',
        ),
    ]
