# Generated by Django 4.2.20 on 2025-06-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options'),
        ('orders', '0008_alter_orderitems_price_alter_orders_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderItems', to='products.product', verbose_name='Товары'),
        ),
    ]
