# Generated by Django 4.2.20 on 2025-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/files/', verbose_name='Файл к заказу'),
        ),
    ]
