# Generated by Django 4.2.20 on 2025-06-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orders_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tracking_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на отслеживание'),
        ),
    ]
