# Generated by Django 4.2.9 on 2025-03-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='speed_count',
            field=models.IntegerField(blank=True, choices=[(6, '6 скоростей'), (9, '9 скоростей'), (12, '12 скоростей')], null=True),
        ),
    ]
