# Generated by Django 4.2.20 on 2025-04-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'price'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
