# Generated by Django 4.2.20 on 2025-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userroles',
            options={'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission', verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Роль пользователя'),
        ),
    ]
