# Generated by Django 4.2.20 on 2025-06-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
